Lutris using Proton 5 depends on libselinux
fixes:
    ImportError: libselinux.so.1
(cherry picked from commit 2d05e1578122cd1c7ea5991eadceb01e5f1951ef)