lutris: add xorg.xkbcomp
```
Traceback (most recent call last):
  File "/nix/store/v1mzyrrnmm9xm7mhqps6pdxdyvkgb154-lutris-original-0.5.6/lib/python3.8/site-packages/lutris/exceptions.py", line 36, in wrapper
    return function(*args, **kwargs)
  File "/nix/store/v1mzyrrnmm9xm7mhqps6pdxdyvkgb154-lutris-original-0.5.6/lib/python3.8/site-packages/lutris/game.py", line 430, in configure_game
    xkbcomp = subprocess.Popen(xkbcomp_command, stdin=subprocess.PIPE)
  File "/nix/store/f87w21b91cws0wbsvyfn5vnlyv491czi-python3-3.8.3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/f87w21b91cws0wbsvyfn5vnlyv491czi-python3-3.8.3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xkbcomp'
```

(cherry picked from commit df99f195e84f0cb0eb7f2b51533198155ea82733)