aseprite-unfree: fix build
It fails with:

src/gpu/gl/glx/GrGLMakeNativeInterface_glx.cpp:15:10: fatal error: GL/glx.h: No such file or directory
   15 | #include <GL/glx.h>

(cherry picked from commit 3ad2c20fe69048e68b49b61717cf911380262320)