lsp-plugins: Fix build
	/build/source/include/metadata/modules.h:122:1: note: in expansion of macro 'MOD_PLUGIN'
	  122 | MOD_PLUGIN(slap_delay_mono, plugin_ui)
	      | ^~~~~~~~~~
	lv2.cpp:414:43: error: invalid conversion from 'void* (*)(const lsp::_LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*)' {aka 'void* (*)(const lsp::_LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)'} to 'void* (*)(const LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*)' {aka 'void* (*)(const LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)'} [-fpermissive]
	  414 |                 d->instantiate          = lv2ui_instantiate;    \
	      |                                           ^~~~~~~~~~~~~~~~~
	      |                                           |
	      |                                           void* (*)(const lsp::_LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*) {aka void* (*)(const lsp::_LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)}

(cherry picked from commit 7ac738273dc7f112c80c7faa9638d7494cc88338)