wasmtime: 20190521 -> 20191018
this upgrade fixes a problem with running trapping WebAssembly code
for me:

```
error: failed to process main module `_out/issue36.wasm`
    caused by: Instantiation error: Trap occurred while invoking start function: wasm trap: unreachable, source location: @2eb9
```

(cherry picked from commit 2c6d1332115910a4bc17c71b80907b4a6f15e7ad)