bash-completion: Fix tests with musl.
Fixes test error

    self = <test_iconv.TestIconv object at 0x7ffff52f3410>
    completion = <CompletionResult []>

        @pytest.mark.complete("iconv -")
        def test_1(self, completion):
    >       assert completion
    E       assert <CompletionResult []>

    ../t/test_iconv.py:7: AssertionError

by applying upstream commit not present in a newer release.

(cherry picked from commit 0a854379c43a257de5fba04a35703134d1faa291)