yle-dl: add setuptools dependency
yle-dl was failing with the following error:

  ImportError: No module named pkg_resources

Adding setuptools to propagatedBuildInputs fixes this issue.

(cherry picked from commit 080da6a65f29ac80848da4a616ffcf8b10a3a5f4)