pythonPackages.seqdiag: disable python2
No longer supported upstream
```
  ERROR: Package 'seqdiag' requires a different Python: 2.7.17 not in '>=3.5'
```

(cherry picked from commit d6e1193d39208ce7c83078ead244694165bbb8bd)