google-cloud-sdk: include openssl(1) in PATH (#77277)
Otherwise, it might fail with a mysterious error:

    ERROR: (gcloud.beta.compute.reset-windows-password) Your platform does not support OpenSSL.

(cherry picked from commit 178ac3cb99a2af4e39fa287ce4774ebb608eef1a)