gns3Packages.{server,gui}Stable: 2.1.21 -> 2.2.0
gns3Packages.{server,gui}Preview: 2.2.0rc5 -> 2.2.0

The new dependency on setuptools is required for pkg_resources:

ImportError: No module named pkg_resources
(cherry picked from commit b52fb3b0789b143e4f4c92972ce62d1880e3b1fe)